name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonacion de codigo
        uses: actions/checkout@v4
  
      - name: Install JDK 1.8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: "8"
          distribution: "temurin"

      - name: Build
        run: mvn package

      - name: Test
        run: mvn clean test

      - name: Report Jacoco
        run: mvn jacoco:report

      - name: Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 100

      - name: Upload Jacoco artifact report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html 

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=matiassalinas \
          -Dsonar.projectKey=matiassalinas_microservicio-java

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: matiassalinas
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Docker build
        run: | 
          docker build -t matiassalinas/microservicio-java:latest .
          
          
      - name: Docker push
        run: | 
          docker push matiassalinas/microservicio-java:latest

  
  deploy:
    needs: build
    runs-on: self-hosted

    steps:

      - name: Clonacion de codigo
        uses: actions/checkout@v4
      
      - name: Despliegue
        run: |
          kubectl apply -f deploy.yaml