name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonacion de codigo
        uses: actions/checkout@v4
  
      - name: Install JDK 1.8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: "8"
          distribution: "temurin"

      - name: Build
        run: mvn package

      - name: Cobertura
        run: mvn verify

      - name: Report Jacoco
        run: mvn jacoco:report

      - name: Upload Jacoco artifact report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html 